Add nm version property getter
phoracek/networkmanager-go pull request #2
Opened 2021-08-31 11:53 UTC by rhrazdil

Add getter for NetworkManager version property 

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

2021-08-31 11:58 UTC, phoracek requested changes

2021-08-31 11:58 UTC, phoracek commented on src/property.go
> +package networkmanager
Let's just name it version.go? Many of the modules work with properties.

2021-08-31 11:58 UTC, phoracek commented on examples/get-version.go
> +  networkmanager "github.com/phoracek/networkmanager-go/src"
I think that this module needs to go through gofmt.

2021-09-14 12:10 UTC, rhrazdil commented on src/property.go
> +package networkmanager
Done

2021-09-14 12:10 UTC, rhrazdil commented on examples/get-version.go
> +  networkmanager "github.com/phoracek/networkmanager-go/src"
Fixed

2021-09-17 10:39 UTC, phoracek approved these changes
Thanks, looks great!

```
[networkmanager-go] go run examples/get-version.go
1.26.8
```

2021-09-17 10:39 UTC, merged